name: PDF Viewer - ReactJS - CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Scan vulnerabilities with Snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Scan vulnerabilities with Horusec
      id: run_horusec
      uses: fike/horusec-action@v0.2.2
      with:
        arguments: -c=horusec-config.json -p ./
